name: electronic_analyzer
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bottleneck=1.4.2=py310hbda83bc_0
  - brotli-python=1.0.9=py310h313beb8_9
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - cclib=1.8.1=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py310h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.27=h60b93bd_7
  - debugpy=1.8.14=py310h853098b_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dkh=1.2=h0bfb809_3
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h1383a14_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.55.3=py310h80987f9_0
  - freetype=2.13.3=hce30654_1
  - gau2grid=2.0.7=hf400cd2_4
  - glib=2.84.0=heee381b_0
  - glib-tools=2.84.0=h1dc7a0c_0
  - greenlet=3.1.1=py310h313beb8_0
  - icu=75.1=hfee45f7_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.4.2=py310hca03da5_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - kiwisolver=1.4.8=py310h313beb8_0
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=h313beb8_0
  - libblas=3.9.0=31_h10e41b3_openblas
  - libboost=1.86.0=hc9fb7c5_3
  - libboost-python=1.86.0=py310hf1156d2_3
  - libcblas=3.9.0=31_hb3479ef_openblas
  - libcxx=20.1.5=ha82da77_0
  - libdeflate=1.24=h5773f1b_0
  - libecpint=1.0.7=hff75ede_12
  - libedit=3.1.20230828=h80987f9_0
  - libexpat=2.7.0=h286801f_0
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.13.3=hce30654_1
  - libfreetype6=2.13.3=h1d14073_1
  - libgfortran=5.0.0=14_2_0_h6c33f7e_103
  - libgfortran5=14.2.0=h6c33f7e_103
  - libglib=2.84.0=hdff4504_0
  - libiconv=1.18=hfe07756_1
  - libint=2.9.0=h2769398_3
  - libintl=0.24.1=h493aca8_0
  - libintl-devel=0.24.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=31_hc9a63f6_openblas
  - liblzma=5.8.1=h39f12f2_1
  - liblzma-devel=5.8.1=h39f12f2_1
  - libntlm=1.8=h5505292_0
  - libopenblas=0.3.29=openmp_hf332438_0
  - libpcm=1.2.3=h5e7a180_15
  - libpng=1.6.47=h3783ad8_0
  - libpq=17.5=h6896619_0
  - librdkit=2025.03.3=hab0a279_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.49.2=h3f77e49_0
  - libtiff=4.7.0=h2f21f7c_5
  - libwebp-base=1.5.0=h2471fea_0
  - libxc-c=7.0.0=cpu_ha287bee_2
  - libxcb=1.17.0=h3fc13f7_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.5=hdb05f8b_0
  - matplotlib-base=3.10.0=py310h7ef442a_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - msgpack-python=1.1.0=py310h7306fd8_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - numexpr=2.10.1=py310h5d9532f_0
  - numpy=2.2.6=py310h4d83441_0
  - openjpeg=2.5.3=h8a3d83b_0
  - openldap=2.6.10=hbe55e7a_0
  - openpyxl=3.1.5=py310h0e452f4_1
  - openssl=3.5.0=h81ee809_1
  - optking=0.3.0=pyhd8ed1ab_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py310hfd37619_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pcmsolver=1.2.3=py_15
  - pcre2=10.44=ha881caa_2
  - periodictable=1.7.1=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.2.1=py310h61efb56_0
  - pint=0.24.4=pyhd8ed1ab_1
  - pip=25.1=pyhc872135_2
  - pixman=0.46.0=h2f9eb0b_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psi4=1.9.1=py310hb2e75c2_10
  - psutil=7.0.0=py310h078409c_0
  - pthread-stubs=0.3=h1a28f6b_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=hd3d436d_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - py3dmol=2.5.0=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycairo=1.23.0=py310hc7d53f0_0
  - pydantic=2.11.4=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py310hb4f9fe2_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.0=py310hca03da5_0
  - python=3.10.17=h6cefb37_0_cpython
  - python-dateutil=2.9.0post0=py310hca03da5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=7_cp310
  - pytz=2024.1=py310hca03da5_0
  - pyyaml=6.0.2=py310hc74094e_2
  - pyzmq=27.0.0=py310h6d25ecc_0
  - qcelemental=0.29.0=pyhd8ed1ab_1
  - qcengine=0.32.0=pyhd8ed1ab_0
  - rdkit=2025.03.3=py310h7378585_0
  - readline=8.2=h1a28f6b_0
  - reportlab=3.5.67=py310h41f7a85_1
  - scikit-learn=1.7.0=py310h48c93d9_0
  - scipy=1.15.2=py310h32ab4ed_0
  - setuptools=78.1.1=py310hca03da5_0
  - six=1.17.0=py310hca03da5_0
  - sqlalchemy=2.0.39=py310hbe2cdee_0
  - sqlite=3.49.2=hd7222ec_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.5.0=py310h33ce5c2_0
  - tk=8.6.13=h5083fa2_1
  - tornado=6.5.1=py310h078409c_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.13.2=h0e9735f_0
  - typing-inspection=0.4.0=pyhd8ed1ab_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py310h80987f9_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310hca03da5_0
  - xlsxwriter=3.2.3=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h3fc13f7_0
  - xorg-libxdmcp=1.1.5=h3fc13f7_0
  - xz=5.8.1=h9a6d368_1
  - xz-gpl-tools=5.8.1=h9a6d368_1
  - xz-tools=5.8.1=h39f12f2_1
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.5=hc1bb282_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - narwhals==2.14.0
      - plotly==6.5.0
prefix: /opt/homebrew/anaconda3/envs/electronic_analyzer
