name: 3D_electronic_analysis_for_site-selecticity
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.7.0
  - appnope=0.1.4
  - asttokens=3.0.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - cairo=1.18.4
  - cclib=1.8.1
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.27
  - debugpy=1.8.14
  - decorator=5.2.1
  - dkh=1.2
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - flexcache=0.3
  - flexparser=0.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.55.3
  - freetype=2.13.3
  - gau2grid=2.0.7
  - glib=2.84.0
  - glib-tools=2.84.0
  - greenlet=3.1.1
  - icu=75.1
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=8.37.0
  - jedi=0.19.2
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libcblas=3.9.0
  - libcxx=20.1.5
  - libdeflate=1.24
  - libecpint=1.0.7
  - libedit=3.1.20230828
  - libexpat=2.7.0
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libglib=2.84.0
  - libiconv=1.18
  - libint=2.9.0
  - libintl=0.24.1
  - libintl-devel=0.24.1
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libntlm=1.8
  - libopenblas=0.3.29
  - libpcm=1.2.3
  - libpng=1.6.47
  - libpq=17.5
  - librdkit=2025.03.3
  - libsodium=1.0.20
  - libsqlite=3.49.2
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxc-c=7.0.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=20.1.5
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - msgpack-python=1.1.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numexpr=2.10.1
  - numpy=2.2.6
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openpyxl=3.1.5
  - openssl=3.5.0
  - optking=0.3.0
  - packaging=25.0
  - pandas=2.2.3
  - parso=0.8.4
  - pcmsolver=1.2.3
  - pcre2=10.44
  - periodictable=1.7.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pint=0.24.4
  - pip=25.1
  - pixman=0.46.0
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psi4=1.9.1
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - py3dmol=2.5.0
  - pybind11-abi=4
  - pycairo=1.23.0
  - pydantic=2.11.4
  - pydantic-core=2.33.2
  - pygments=2.19.1
  - pyparsing=3.2.0
  - python=3.10.17
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - qcelemental=0.29.0
  - qcengine=0.32.0
  - rdkit=2025.03.3
  - readline=8.2
  - reportlab=3.5.67
  - scikit-learn=1.7.0
  - scipy=1.15.2
  - setuptools=78.1.1
  - six=1.17.0
  - sqlalchemy=2.0.39
  - sqlite=3.49.2
  - stack_data=0.6.3
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.13.2
  - typing-inspection=0.4.0
  - typing_extensions=4.13.2
  - tzdata=2025b
  - unicodedata2=15.1.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xlsxwriter=3.2.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - narwhals==2.14.0
      - plotly==6.5.0
